### ISSUE TITLE
Giving users advanced warning when opening a new window

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#100]
This commit introduced an icon on all links https://github.com/joomla/backend-template/commit/200dab6c3c4947f7f6f6e011ffaf43fc9195d630

From the comment in the code I assume it was intended for external links however it is being applied to all links that begin with http

I am guessing that the intent of this PR was to satisfy an a11y requirement 

The requirement is to provide an indicator if a link opens in a NEW window/tab

The indicator should not be limited to sighted users as obviously that fails the requirement

The links that need to be addressed are just those with a target
https://www.w3.org/TR/WCAG20-TECHS/H83.html

**Comment by chmst** [comment]
The aim was to make links visible also for color blind who cannot distinguish links and texts only from  colours.
We can choose to do this via text-decoration: underline or by adding an icon (css only) which indicates a link. 
Underline is no solution - it looks awkward 
Do you know an icon which indicates an internal link?

**Comment by brianteeman** [comment]
> The aim was to make links visible also for color blind who cannot distinguish links and texts only from colours.

It really is confusing two different issues. Indicating that a link opens in a new window and ensuring that all links are clearly marked as links.

As well as the icon issue the code is only being applied to some links and not all links

> We can choose to do this via text-decoration: underline or by adding an icon (css only) which indicates a link.
> Underline is no solution - it looks awkward

text-decoration is the norm it doesnt have to be a solid line
![image](https://user-images.githubusercontent.com/1296369/55721506-740a3480-59fb-11e9-9bd1-25a7c6088e65.png)

> Do you know an icon which indicates an internal link?

No and I wouldn't recommend that route.

**Comment by brianteeman** [comment]
CSS only method for external link indicator https://codepen.io/brianteeman/pen/zXpJWy?

**Comment by bembelimen** [comment]
Perhaps we should combine the current solution + your solution: ```a[target="_blank"][href*="//"]:not([href*="javascript://"])``` because not all blank are external and not all ```//``` are external. (The proper solution would be to check for the Domain, but I guess that's not possible)

**Comment by brianteeman** [comment]
I stand by my original comment it is nothing to do with a link being to a different domain- quoted below for email

> The requirement is to provide an indicator if a link opens in a NEW window/tab
The indicator should not be limited to sighted users as obviously that fails the requirement
The links that need to be addressed are just those with a target
https://www.w3.org/TR/WCAG20-TECHS/H83.html

**Comment by coolcat-creations** [comment]
A new tab could maybe be indicated by this icon? 
https://fontawesome.com/icons/window-restore?style=regular
And the external link by the external link symbol?

Where does a new Tab open in backend to internal pages ?

**Comment by brianteeman** [comment]
I stand by my original comment. There is no need to indicate if a link that opens in a new tab is to the same domain or to a different domain. https://www.w3.org/TR/WCAG20-TECHS/H83.html

**Comment by nadjak77** [comment]
the icon onlay appears if target=_blank is set
Commit: 76e5b09c358d6320b817f62ffd6509c42708d1bf [76e5b09]
