### ISSUE TITLE
Not the backend

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#102]
This commit https://github.com/joomla/backend-template/commit/443f4a72d1f3562089091f083084c5b742e5a2a5 introduced a new language string TPL_ATUM_LOGIN_HEADING of "Joomla Backend Login"

![image](https://user-images.githubusercontent.com/1296369/55649978-5ad76d00-57dc-11e9-9b24-34362ad3a769.png)

There are two issues
1. We already have a string for this TPL_ATUM_BACKEND_LOGIN so either that one should have been used or it should have been removed
2. The text really should have been "Joomla Administrator Login" for consistency with the rest of joomla where we call it Administrator

**Comment by coolcat-creations** [comment]
thank you, it's fixed

**Comment by brianteeman** [comment]
direct unreferenced commits completely suck. they make it impossible to have any sort of history of why a change was made.

**Comment by coolcat-creations** [comment]
> direct unreferenced commits completely suck.

You can say this in a nice way. I give you an example:

"Can you please commit the next time with reference to this issue so there is any sort of history."

**Comment by brianteeman** [comment]
Already tried. Gave up when you made personal attacks

**Comment by coolcat-creations** [comment]
You are the one attacking personally. Over and Over again. Stop it.

**Comment by brianteeman** [comment]
Lol
