### ISSUE TITLE
Non translated module

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#103]
The new module in the admin "Need Support" should be using language strings and not raw text. We already have the strings in mod_menu.ini and com_cpanel.ini and just like in the help component it should support MOD_MENU_HELP_SUPPORT_CUSTOM_FORUM

**Comment by brianteeman** [comment]
It also results in FIVE extra queries on the login page

**Comment by chmst** [comment]
The "need support" is a quite normal custom module on position "sidebar"where every Installation can add it's own support options, for example a Help desk, the name of the administrator or something quite different. 
What we have here is an example in english  installation sql file.

**Comment by brianteeman** [comment]
We already have the code for every site to add its own support options.

**Comment by chmst** [comment]
Rigth. But I don't see the problem. 
If an administrator does not want it, he can disable the module. Or override the logn page and place other positions.

**Comment by brianteeman** [comment]
Better to just remove this. From my perspective the content of this module is way beyond the scope of the design of the admin template

**Comment by nadjak77** [comment]
changed to language strings 
https://github.com/joomla/backend-template/pull/273
