### ISSUE TITLE
MOD_LOGIN_CREDENTIALS_LINK localisation

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#105]
Any link to the docs site should be using the special url format of Special:MyLanguage as can be seen in all links in joomla to the docs website. This ensures that if the page is in french then the user will be sent to the french translation of the page.

so in this case the url should be

`https://docs.joomla.org/Special:MyLanguage/How_do_you_recover_or_reset_your_admin_password%3F`

**Comment by coolcat-creations** [comment]
Closed as we have a commit https://github.com/joomla/backend-template/issues/105
