### ISSUE TITLE
H42: Using h1-h6 to identify headings

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#106]
On the login page the first heading on the page is not a heading 1 (H1 or WAI-ARIA role="heading" aria-level="1") but an h2

To give your document a proper structure for assistive technologies, it is important to lay out your headings beginning with an h1 

The order of the headings is
H2 Site Name
H3 Need Support
H1 Login

**Comment by zwiastunsw** [comment]
On the login page **we have only one element of content** - the login form. Why here are the **two headings**: H1 and H2?
If you want to add a site name, add it to the heading, which contains the title of the page and not to a separate heading.  
In my opinion, the name of the website is not needed here at all. It is visible in the browser bar.

**Comment by chmst** [comment]
@zwiastunsw @brianteeman please test this solution. It needs a new installation or manual settings of the "Need Help" Module. The parameter "Show Title header" must be set to "no".

**Comment by chmst** [comment]
Closed assolved in PR #140
