### ISSUE TITLE
COM_LOGIN_TWOFACTOR

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#107]
This new string added with https://github.com/joomla/backend-template/commit/d3c007ca82990a17d644f42b2b18379eae84dcf3 is incorrect

It should be 
1. Alpha sorted
2. "Two" not 2

**Comment by coolcat-creations** [comment]
Closed as we have a commit b1d981300e9aae3ab42d23bff6173ff5e4a795f2 [b1d9813]
