### ISSUE TITLE
Two Factor error message

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#108]
### Steps to reproduce the issue
Enable the two factor authentication plugin but do NOT set it up for the user
Login using a fake two factor authentication

### Expected result
Successful login and message on control panel as below
![40dev](https://user-images.githubusercontent.com/1296369/55667749-6e281e00-5858-11e9-8831-003510954702.gif)

### Actual result
Successful login and message displayed on the module very briefly before control panel (eventually) loads with no error message
![backend](https://user-images.githubusercontent.com/1296369/55667754-8730cf00-5858-11e9-8534-541c4bfb79fe.gif)

**Comment by coolcat-creations** [comment]
@bembelimen is this a template related issue or System?

**Comment by bembelimen** [comment]
Thx https://github.com/joomla/backend-template/pull/285
