### ISSUE TITLE
Two factor alignment - mobile

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#109]
On desktop the text is aligned right
![image](https://user-images.githubusercontent.com/1296369/55667802-1fc74f00-5859-11e9-937b-1852a33f5439.png)

On mobile the align right doesn't work
![image](https://user-images.githubusercontent.com/1296369/55667822-53a27480-5859-11e9-8755-7223c656868b.png)

**Comment by coolcat-creations** [comment]
Closed as we have a commit 3869d3f22169d05829bad74b84d5a400c5eb646f
