### ISSUE TITLE
Login page - important image without alt attribute

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/backend-template#111]
In the header of the login page we have only the Joomla logo. This logo **is important** for the content of this section and this page. It must have an alternative description. Alt attribute cannot be empty in this case!

**Comment by brianteeman** [comment]
My initial thought is that this is not important at all and is just decorative so correctly does not have an alt attribute.

But as this image can be customised by the user that might not alway be the case

**Comment by chmst** [comment]
It was thought of beeing pure decorative and therefore does not need an alt text.

**Comment by brianteeman** [comment]
@chmst I agree with you when it is the joomla logo but as it is customisable then it might not be decorative in that case

**Comment by zwiastunsw** [comment]
In  my opinion logo **in the page header** is not a purely decorative picture. It is always an important picture.

**Comment by chmst** [comment]
Indeed. So the issue is confirmed (for user specific images). Jor Joomla icon - I am not conviced.

**Comment by zwiastunsw** [comment]
I am talking only about the Joomla logo in the header of the page. I'm not talking about the icon above the login form.

**Comment by brianteeman** [comment]
@zwiastunsw yes we know which image you refer to - we're just not convinced it is important

**Comment by chmst** [comment]
Closed. Alt texts are possible.
