### ISSUE TITLE
Login page - fieldset does not have an accessible name

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/backend-template#112]
The fields of the login form have been tagged as fieldset.  A fieldset does not have a legend.

A fieldset legend presents a description of the form elements within a fieldset and is especially useful to screen reader users. A legend should be provided when a higher level description is necessary for groups form controls.

A sighted user can see that he is dealing with a login form. He immediately realizes that he has a group of fields to fill in. A blind user does not know about it. If a group of fields does not have an accessible name, it is not announced by the screen reader.

If a higher level description is necessary for the user to understand the function or purpose of the controls within the fieldset, provide this description within the `<legend>`. If this description or grouping is not necessary, the fieldset should probably be removed. 

If you don't want to show the legend on the screen, just add sr-only class to it.

**Comment by chmst** [comment]
This is not related to the backend template, it is for admin module mod_login. The issue should be transferred to  joomla_cms.

**Comment by brianteeman** [comment]
@chmst if this repo was only changes to the template that would be true. Unfortunately we both know the majority of the changes here are not template related but in a whim of the designer

**Comment by chmst** [comment]
We separate concerns but it is not always possible. I will fix this issue on joomla-cms.

**Comment by bembelimen** [comment]
Thx @chmst
