### ISSUE TITLE
Login page - illogical arrangement of page elements

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/backend-template#113]
The most important part of the login page is the login form. When you enter the login page, the focus of your keyboard should be placed immediately in the first field of the login form. This was the case in Joomla 3 and earlier.  And so it should be. This is the common expectation of the user.
Now the user must position the cursor himself in the form field. The keyboard user must use the Tab key twice, because the first item on the page is... link to the front page.  This is illogical. It does not make sense! That's not why I call the backend login page to go to the front page.

**Comment by brianteeman** [comment]
I cannot confirm this. The focus in a page load is the username field

**Comment by zwiastunsw** [comment]
Indeed. The focus automatically moves to the login field. I had to be very tired.
However, I still support the basic thesis. When you navigate through the page using the keyboard, the order of reading (focus) should follow the visual and logical order. In this case, the order of reading is distorted.

**Comment by bembelimen** [comment]
Hello @zwiastunsw could you please elaborate a bit more, for me the ordering is: user name => password => show PW => Login button => Forgot PW

Which ordering would you prefere?

**Comment by zwiastunsw** [comment]
The fragment of the reading order you wrote down is OK. 
But on the login page there is one more element in the reading order:
Visual: **View website**=>Username=>Password=>Show PW=>Login button=>Forgot credentials 
Actual (key Tab):  Username=>Password=>Show PW=>Login button=>Forgot credentials=>**Browser address bar**=>**View website**.  This is illogical. It does not make sense! 
Link **View website** should be the last in the order of reading (and tabulation), after the link Forgot credentials.

**Comment by bembelimen** [comment]
Fixed. Thx.
