### ISSUE TITLE
Login page - Unclear link

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/backend-template#114]
The link *Forgot your credentials?*, which leads to the help page, is unclear. 

First of all, the word "credentials" is difficult, not only in English.
Secondly. Links in login forms, such as "Forgot your name?", "Forgot your password?" lead by default to pages that allow you to send a request for change/reminder password/name, and not to instructions in the help system.

The corrected text of the link should clearly indicate that it leads to a help system.

**Comment by brianteeman** [comment]
I have no issue with this. Credentials seems the correct word to me. The reasoning behind the change to link to the help system is I guess because the previous links dont work for a super user

**Comment by zwiastunsw** [comment]
Why not use the words "login data"? *Forgot your login data?*
I also have no problem with the word 'credantials'. But when translated into Polish it will be a very difficult, long and rarely used phrase: "Zapomniałeś swoich danych ***uwierzytelniających***". The word "uwierzytelniających" has as many as 19 characters and 7 syllables. The word "logowanie" has only 8 characters and 3 syllables. 
The third principle of accessibility - Understandable - requires the use of simple language.

**Comment by brianteeman** [comment]
The words "login data" would be very unusual in english compare to "credentials"

In this example of yours it is, as always, the responsibility of the polish translator to "localise" the text and not simply translate it

**Comment by jeckodevelopment** [comment]
I'd stick to "credentials" instead of login data.
Translators can localise to the appropriate match in target language

**Comment by zwiastunsw** [comment]
OK. This is a language problem. And in this respect @brianteeman is an authority for me :).

**Comment by chmst** [comment]
Thank you. For me as German "credentials" sound strange too and in German it will be translated with something like "Zugangsdaten" or like Google says "Problems with your account?"
If you think, that's all right, could you close this issue?
