### ISSUE TITLE
Admin Menu - multiple lines

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#118]
In this version of the menu we now see some menu items being spread on to two lines. Thats fine but then you need to adjust the line height so that they look like one item and not two

### Current
![image](https://user-images.githubusercontent.com/1296369/55719274-c2b4d000-59f5-11e9-9532-c775f444c629.png)

### Example
![image](https://user-images.githubusercontent.com/1296369/55719341-e2e48f00-59f5-11e9-917c-a6340fe65554.png)

**Comment by sanderpotjer** [comment]
Current status:
<img width="268" alt="Screenshot 2019-05-05 at 13 07 00" src="https://user-images.githubusercontent.com/522834/57192975-b9f0e480-6f36-11e9-9be6-307204b3bf5d.png">

Closing this issue. Thanks @brianteeman & @karo3
