### ISSUE TITLE
Admin menu - Dashboard onhover

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#119]
All the links in the admin menu have a really obvious styling for onhover except for the dashboard icons 

### Menu Item
![image](https://user-images.githubusercontent.com/1296369/55719426-19baa500-59f6-11e9-839e-60fe5691cd2c.png)

### New Item
![image](https://user-images.githubusercontent.com/1296369/55719453-2808c100-59f6-11e9-802d-d7d85ab46f4c.png)

### Dashboard item
![image](https://user-images.githubusercontent.com/1296369/55719472-3bb42780-59f6-11e9-88fd-2823eebedda9.png)

**Comment by coolcat-creations** [comment]
Closed as we have a commit 6cea6b49cf4277b62e7a2eae9843770a7f15644f
