### ISSUE TITLE
Admin menu - new item links [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#121]
Every "new item" link has the same name which is a big problem and needs to be addressed. It is very common for example for a screen reader user to press a hot key that will list all the links on a page

**2.4.4 Link Purpose (In Context)**
The same link text is used for links going to different destinations. Users might not know the difference if they are not somehow explained.

Make sure links are distinguishable by just their link texts or WAI-ARIA labels ('aria-labelledby' or 'aria-label') to make it clear that they lead to different destinations.

Possible solution is to make sure that instead of saying "new item" it says "new article" etc

**Comment by drmenzelit** [comment]
Changes done for joomla.xml preset in commit 4e8a2c8cf07b37f82547c9bb0d835284566be4e5

Please close if this solve the problem.

**Comment by brianteeman** [comment]
Looks good now - thanks
