### ISSUE TITLE
Every dashboard has the same title [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#126]
As the issue says - every page that is a dashboard has the same page title of Control Panel - obviously this should be changed so that they are unique

![image](https://user-images.githubusercontent.com/1296369/55721059-45d82500-59fa-11e9-82e7-9107e3cbdd25.png)

![image](https://user-images.githubusercontent.com/1296369/55720972-0c9fb500-59fa-11e9-8ba0-1470fb9f1ba8.png)

![image](https://user-images.githubusercontent.com/1296369/55720989-1a553a80-59fa-11e9-861d-1f41cda1023b.png)

![image](https://user-images.githubusercontent.com/1296369/55721002-23dea280-59fa-11e9-8187-a326001b7b90.png)

![image](https://user-images.githubusercontent.com/1296369/55721016-2d680a80-59fa-11e9-898d-baf64c5a0122.png)

![image](https://user-images.githubusercontent.com/1296369/55721036-3a84f980-59fa-11e9-9dbe-f9ecdec22cab.png)

**Comment by coolcat-creations** [comment]
@Hackwar can you lead me where to edit this?

**Comment by wilsonge** [comment]
https://github.com/joomla/backend-template/blob/release/administrator/components/com_cpanel/View/Cpanel/HtmlView.php#L60

**Comment by bembelimen** [comment]
Thx @chmst
