### ISSUE TITLE
Mobile view - menu selector

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#127]
At first I thought there wasn't a menu at all on the mobile view

I certainly didn't expect it to be what it is. Is this a common design pattern?

![image](https://user-images.githubusercontent.com/1296369/55721267-ca2aa800-59fa-11e9-938c-21190a888e4f.png)

**Comment by coolcat-creations** [comment]
Closed as we have a commit (Changed to burger icon) #c0c624f
