### ISSUE TITLE
Save button icon

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#128]
I am confused. The current save button uses an edit icon which is obviously wrong
![image](https://user-images.githubusercontent.com/1296369/55722977-a453d200-59ff-11e9-9156-596bda6af457.png)

https://github.com/joomla/backend-template/issues/36 says that it should be a disk icon and that it has been fixed with https://github.com/joomla/backend-template/pull/59 

#59 makes no changes to the save icon it only has changes for the status

**Comment by lavipr** [comment]
Indeed the save-icon has to be replaced.
#59 has changes to the drop-down list, so there are changes that also affect the Save button.

**Comment by lavipr** [comment]
Fixed with 5aa2d07

**Comment by bembelimen** [comment]
Thx
