### ISSUE TITLE
Settings icon

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#132]
The icon used for setup in the system dashboard is the same a the icon used to indicate that you can "edit" the module.

Its particularly obvious/confusing on smaller resolutions but it needs fixing on all of them - probably by choosing a different icon for setup

<img width="1085" alt="chrome_2019-04-09_12-25-07" src="https://user-images.githubusercontent.com/1296369/55796844-cfebc080-5ac2-11e9-9a79-d0e71bb4cf82.png">

![image](https://user-images.githubusercontent.com/1296369/55796879-e4c85400-5ac2-11e9-89d8-a281dd494164.png)

**Comment by chmst** [comment]
Please have a look here: https://github.com/joomla/backend-template/pull/138

**Comment by chmst** [comment]
Replace the coq for System Settings by a wrench. As soon as the new version of fontawesome is available, the wrench can be replaces by icon fa-tools.

**Comment by chmst** [comment]
Closed - see pr #138
