### ISSUE TITLE
RFC: Logo should not be in template logo should be a module

### ISSUE THREAD

**Issue by uglyeoin** [joomla/backend-template#141]
### Is your feature request related to a problem? Please describe.
Just an idea, I can see the benefit of having the logo as an editable item in the template but it's the only place you find an image used in this way.  It's also the only template setting.

### Describe the solution you'd like
I think it would be better placed as a module.  I would also expect to see microdata or LDAP Json accompanying it.  I already have this module in existance for Joomla! 3 which allows you to use an image, text or an image and text and set the URL if necessary.  I would be happy to provide it if you think it would help.  I'd be happy to create an equivalent Admin version.

I haven't added description but I could do.  

I don't see where "title" appears in the source code although I filled it in within the template text field.

**Comment by wilsonge** [comment]
LDAP microdata is beyond scope of here. It’s actually in our planned gsoc seo project (if we’ve got any students who have applied for it).

My personal opinion is branding is the focus of the template (it sits alongside colour themes). But I’m happy for that to be under discussion.

**Comment by uglyeoin** [comment]
I guess just because it might be coming doesn't necessarily mean it should be blocked beforehand.  That would be first argument. And as I m offering pre-written code it shouldn't block or delay anything if that is a concern. 

But also the question is whether it is logical to have  it in the template or as a module. And if front end editing is turned on, would being in the template mean it is one of the few uneditable items?

**Comment by bembelimen** [comment]
Hello @uglyeoin do you speak about backend or frontend?

**Comment by coolcat-creations** [comment]
@uglyeoin can you clarify if you speak about the backend template? thanks

**Comment by uglyeoin** [comment]
Sorry, I refer to the front end template but I consider that both would work as a module.

**Comment by coolcat-creations** [comment]
So this is the backend repo and frontend is out of scope. I suppose to close the issue here then?

**Comment by uglyeoin** [comment]
Ah I see.  Well in that case I feel like if we're doing it for the front end we should be consistent and do it as a module in the back end too.  Can we discuss prior to closing?

**Comment by uglyeoin** [comment]
Sorry there is no logo in the backend. Yes let's close

**Comment by coolcat-creations** [comment]
Of course there is a logo in the backend...!

I throw in a new possibility: What about a logo plugin where you can manage vendor and site Logos with repeatable fields and their respective favicons (not only favicon but also appletouch, android settings, windowstile) - I can provide the base of the plugin here to merge into core, someone would need to add the possibility to make it repeatable and to check the code at all. Other areas, Components, Templates etc. could take the parameters of this plugin.

https://github.com/coolcat-creations/DBfavicon

**Comment by uglyeoin** [comment]
For a site creator they will want to brand the backend as either their own or as the clients own.  Much of the time that will include a favicon for sure, but also a logo.  This shouldn't always be a favicon.  We definitely want site builders on our side (and agencies)

As another note there's no alt text on the Joomla! logo in the back end which the accessibility team probably need to know about, unless this is deliberate because it is decorative only.  I'd consider it branding so not purely decorative so worth mentioning.

Plugin/Module I'm not so fussed about, you are probably better positioned to understand which route makes more sense than I am.  I prefer a module because of where it is located and because potentially you may want more than one.  If you are using a plugin with repeatable fields and one of the fields is the module position then I think a module is more sensible.

**Comment by coolcat-creations** [comment]
> For a site creator they will want to brand the backend as either their own or as the clients own. Much of the time that will include a favicon for sure, but also a logo. This shouldn't always be a favicon. We definitely want site builders on our side (and agencies)

Yes i thought about a repeatable field because then someone comes around and says that pages xyz have another Logo and they need some kind of parameters. So just including repeatable fields from the beginning to avoid later pain. But I have to say that is all not really in scope of this repo since it would be a feature request for the main repo. Anyway maybe @bembelimen can say if my plugin is worth anything to be included in the core?

> As another note there's no alt text on the Joomla! logo in the back end which the accessibility team probably need to know about, unless this is deliberate because it is decorative only. I'd consider it branding so not purely decorative so worth mentioning.

Yes there is an issue open about this :)

> Plugin/Module I'm not so fussed about, you are probably better positioned to understand which route makes more sense than I am. I prefer a module because of where it is located and because potentially you may want more than one. If you are using a plugin with repeatable fields and one of the fields is the module position then I think a module is more sensible.

I tought about a plugin because you could use it then in frontent and backend. There is no Module for front AND backend :)

**Comment by uglyeoin** [comment]
> 

> I tought about a plugin because you could use it then in frontent and backend. There is no Module for front AND backend :)

Oh, I see, that makes sense.  I was thinking that people may possibly use a front end module more than once in more than one position.  For example a site integrator may wish to use their logo in the footer stating they built the site for example.  Anyway, if this is not for this repository then let's close it.

**Comment by wilsonge** [comment]
If you're doing it like this then the logo AND the colour schemes should be in the same plugin. But tbh personally I consider the template responsible for branding decisions (the frontend and backend colour schemes are definitely not necessarily the same things)

**Comment by uglyeoin** [comment]
I would consider the colour scheme directly related to the template.  I don't see that anywhere in the Admin to change the colour settings so I assume it will be CSS based.

I would consider a logo to be a reusable item.  I've had cases where the client needs two logos in the header (because they are authorised by someone for example; or part of a larger group).  Both logos would ideally be individual rather than an image showing both.  This means they can have their own microdata, alt tags etc.  I've also seen logos used in sidebars and footers.  Thus I think it should be a reusable asset i.e. a module.

**Comment by coolcat-creations** [comment]
I am closing this since I think it's something for the main repo, if someone disagrees please reopen.
