### ISSUE TITLE
Go to System > and then anything else

### ISSUE THREAD

**Issue by uglyeoin** [joomla/backend-template#142]
### Steps to reproduce the issue
First example:
Go to system.  
Click any option.
But I have selected the wrong option by accident

Second example:
Go to system
Click on Global Configuration
This time there is a close button.
I click it
It does not take me back to the screen before it takes me to the dashboard/cpanel

### Expected result
First option:
I look for a close or a back button

### Actual result
First option:
I have to click on system.

Second Option:
I have to click on System or am confused as to what screen I have come to.

### System information (as much as possible)

[systeminfo-2019-04-17T11_09_01-04_00.txt](https://github.com/joomla/backend-template/files/3090326/systeminfo-2019-04-17T11_09_01-04_00.txt)

### Additional comments
I think there should be a close button that takes you back to system on all pages.  I see this as a usability issue I found it confusing I think others would too.

**Comment by bembelimen** [comment]
Hello @uglyeoin thank you for your input. I think you have some valids points here, but unfortunately it's out of our scope (as backend template team).

Could you please open a new issue in the public tracker? https://github.com/joomla/joomla-cms/issues

Thank you!
