### ISSUE TITLE
Dashboards - make the links more accessible 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#150]
### What needs to be fixed
The dashboards are there to create a better accessibilty and overview.
Currently only the linktext or the small icon are clickable.

### Why this should be fixed
The layout has to be fixed so that the clickable area is larger. (For handling it with a mouthstick or similar)

### How would you fix it
larger clickable area

**Comment by chmst** [comment]
@coolcat-creations please test

**Comment by coolcat-creations** [comment]
halfway there @chmst - now the plus icons are in the second row.

**Comment by chmst** [comment]
The PR resolves this. The quicktask is small - I suppose a change in design

**Comment by coolcat-creations** [comment]
Thank you!
