### ISSUE TITLE
System dashboard missing after installation 

### ISSUE THREAD

**Issue by chmst** [joomla/backend-template#154]
### Steps to reproduce the issue
Make a new installation with a new database

### Expected result
The system panel (dashboard) has all links to all functions

### Actual result
The system panel is empty, also all other dashboards, so no administration is possible. 
The administrator submenu is not installed (in the database) 
Install it via discover, thane make all settings - the style and bootstrap sizes are wrong

Thanks @degobbis .
 
### Additional comments
The Dashboards need a very good documentation or very much must be hidden or explained. for example user see the position cpanel-system for a dashboard. They don't know that the name is generated ..

**Comment by coolcat-creations** [comment]
Is this resolved? :)

**Comment by chmst** [comment]
Resolved
