### ISSUE TITLE
dashboards broken??

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#170]
### Steps to reproduce the issue
clean install of release branch at time of posting

![image](https://user-images.githubusercontent.com/1296369/57241394-c6556a00-7028-11e9-8873-8301f2ed9aa8.png)

**Comment by brianteeman** [comment]
Looks like all the forms are broken as well

![image](https://user-images.githubusercontent.com/1296369/57241932-1b45b000-702a-11e9-888b-73c52b72ef05.png)

**Comment by brianteeman** [comment]
Looks like dashboard changes have been fixed but form errors still present

**Comment by coolcat-creations** [comment]
Could be that you need to reinstall the release branch + npm i

**Comment by Hackwar** [comment]
Can you check that again? For me, the current release branch looks okay, at least in comparison to your screenshots.

**Comment by brianteeman** [comment]
The form in the screenshot - user notes - looks exactly as in the screenshot with the current release.

If you are saying that it is correct that all fields are 100% width then thats a big usability issue especially for the fields that have a button appended at the end. Another example of this bad ui/ux can be seen on the new user form

Also as can be seen in the zoomed section below some of those buttons are missing or styled incorrectly

![image](https://user-images.githubusercontent.com/1296369/57521360-fa29db80-7317-11e9-9031-98a9cb205ae5.png)

**Comment by brianteeman** [comment]
Also making the fields 100% width has broken the switcher fields - as the css for them puts the legend where the label was (-220px) but the change has meant the legend is now off the screen

**Comment by coolcat-creations** [comment]
Hm your Screenshot don’t look like the repo I worked on. But part of the changes I did look like they had been removed or maybe only partly. I don’t understand what had been done with all the commits.... 

you can achieve 100 percent with with the class btn-block if you need it to... 

The thing is that I can’t make a complete PR without help fixing the html structures.

**Comment by coolcat-creations** [comment]
The repo was torn apart because of the dropdowns, I did not do the File select in detail yet but it definetly looks different thank in the screenshot you posted. <img width="380" alt="grafik" src="https://user-images.githubusercontent.com/828371/57529393-14be7d80-7335-11e9-8029-e2b50c1e3a6f.png">

**Comment by Hackwar** [comment]
@brianteeman You are right, the forms right now need more work. I was mostly refering to the dashboards, which you were talking about in the initial comment. Could you confirm that the dashboards have improved? They are not done yet, but they should look better than your screenshot above.

@coolcat-creations The repo was not torn apart. A series of commits that broke the backend and were obviously not ready to be merged, was moved out to another branch for the original author to work on it there further. When the change is finished, it can be merged into the release branch again, but half-finished work has no business in the release branch. Yes @brianteeman, we did not enforce that enough in the beginning and we are being bitten by that now. We are all doing our best to fix it.

**Comment by coolcat-creations** [comment]
@Hackwar ok so hopefully someone can fix it.

**Comment by brianteeman** [comment]
@Hackwar yes i can confirm the dashboards are improved. as i stated https://github.com/joomla/backend-template/issues/170#issuecomment-490049720

**Comment by Hackwar** [comment]
The dashboards are working again and that was the initial report of this issue. The forms still need work and we are on it, but that would be another issue and thus for now I'm closing this one.
