### ISSUE TITLE
joomla-toolbar-button 

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#193]
![image](https://user-images.githubusercontent.com/1296369/57521705-e468e600-7318-11e9-818a-7306ef4e9d50.png)

If you look at the image you can see that there is a blank line with a grey vertical line before each button.

This is coming from 
```
joomla-toolbar-button {
    border: 1px solid var(--border);
}
```

If that css is removed then you get the following which I am sure is the intended view?
![image](https://user-images.githubusercontent.com/1296369/57521838-3873ca80-7319-11e9-9ee7-8ae1c36fdce1.png)

You can also see an issue with the "Batch" text being aligned differently to the other buttons. This is because the icon for the other buttons have a width of 26px coming from
```
.btn-group .dropdown-menu [class*=" icon-"], .btn-group .dropdown-menu [class^=icon-] {
    width: 26px;
}
```
As the batch is using `class="fa fa-square"` the css above is not being applied

**Comment by Hackwar** [comment]
We have a PR (#268). Closing this one.
