### ISSUE TITLE
Clear button no longer works as intended

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#240]
In any list view there is a clear button - the intent of this button is to reset any filters that have been set and that includes a search filter.

In the joomla 4 repo you can see how it should work but in this repo the button is disabled unless there is a filter set.  In order to  clear a search you need to delete the search term and refresh the page

### Joomla 4
![search4](https://user-images.githubusercontent.com/1296369/58379964-8b4cb380-7fa2-11e9-9114-44e37b936073.gif)

**Comment by bembelimen** [comment]
Should be fixed with: https://github.com/joomla/backend-template/pull/318
