### ISSUE TITLE
Merging shouldn't make it worse

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#253]
I know @Hackwar has said this before but it clearly needs repeating. When a PR is merged it shouldn't make things worse. Every time I update my clone and rebuild the css etc then the template is breaking in different places.

And PLEASE PLEASE provide details in the pull request of what has been changed and why. That's one of the reasons merges are breaking things because it is completely unclear most of the time what the change is for. There are too many pull requests that just say

![image](https://user-images.githubusercontent.com/1296369/58385293-f7044000-7fe5-11e9-80bb-d0e53d65d6f9.png)

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/58386015-a98dd000-7ff1-11e9-867c-623016c52741.png)

**Comment by Hackwar** [comment]
You are right and the volunteers have again been made aware of that. 

In order to clean up the tracker, I'm going to close this issue. Thank you for the reminder.

**Comment by brianteeman** [comment]
Doesnt seem to stop bad pr being merged

**Comment by brianteeman** [comment]
Perhaps you will clean up the pull requests by removing all those that are incomplete (or at the minimum not merging them until they are complete)

**Comment by Hackwar** [comment]
Incomplete PRs should normally be marked as Draft. Anyway, we will do our best to clean up that list, too. We all want to come to a finish with this project...
