### ISSUE TITLE
Language String Code Style

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#255]
We have a style guide for en-gb language strings in the ui. https://developer.joomla.org/en-gb-user-interface-text-guidelines/introduction.html

The relevant part for this bug report is

> use capitalisation for:
Menu Items
Labels
Buttons

The following are not following the style guide

COM_CPANEL_DASHBOARD_HELP_TITLE="HELP"

and 

```
.view-login .login #btn-login-submit {
    text-transform: uppercase;
    background: var(--atum-bg-dark);
    color: hsla(0,0%,100%,.8);
}
```

**Comment by bembelimen** [comment]
Fixed with https://github.com/joomla/backend-template/pull/284/commits/f77c62b4207e62fbabcf44a88a3facfe39743f90
