### ISSUE TITLE
New items on the help dashboard

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#259]
I note that there are several new items on the dashboard that are **not** help related. They really should not have been added here in this repo as they are **not** template related. In addition it has already been discussed many times on the main repo that these non-help related links do not belong in the install.

Please revert the addition of new links from this repo and create a PR in the main repo for the new links

**Comment by brianteeman** [comment]
To be clear I am referring to the 
Meet Joomlers, News, Get involved groups

**Comment by wilsonge** [comment]
Going to close this in favour of the same issue in the main repo as we're going to merge in there soon https://github.com/joomla/joomla-cms/issues/21990
