### ISSUE TITLE
Icons in circles

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#263]
If you compare the two screenshots below you will see that the icons in this repo are not centred.

For some reason the font size for the `tbody-icon` class is deciding that 1rem = 16px on this repo but 15px on the main repo. Sorry but this sort of css is mystical magic to me

### This repo
![image](https://user-images.githubusercontent.com/1296369/58433899-fe445000-80b0-11e9-932c-2b681f3ea502.png)

### Main repo
![image](https://user-images.githubusercontent.com/1296369/58433916-0e5c2f80-80b1-11e9-935e-1ad71a6efe9c.png)

**Comment by bembelimen** [comment]
Hi @brianteeman the icons look quit ok for me now (I guess from the Fontawesome update you did), could you confirm this please?

![grafik](https://user-images.githubusercontent.com/1229869/60519420-ca79cd00-9ce3-11e9-9488-116bea5abfaa.png)

![grafik](https://user-images.githubusercontent.com/1229869/60519470-e5e4d800-9ce3-11e9-9763-3e201dd70669.png)

**Comment by brianteeman** [comment]
yes looks ok now

**Comment by bembelimen** [comment]
Thx
