### ISSUE TITLE
Add components to System

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#264]
With the new system dashboard is there a way for extension developers to install their components there instead of the components menu?

**Comment by Hackwar** [comment]
The short answer is "no", the long answer is:

The dashboards are a component view to display modules. A component could bring along their own module that they install and create an instance that they place on a dashboard. That is of course not adding the component menu entries into the mod_submenu modules. mod_submenu displays either a custom backend menu or an XML preset. Effectively it is not feasible to insert menu items there; you would either have to have a custom menu already present and insert your entries there or modify the preset. The logic that inserts the component menu entries into mod_submenu dynamically is a special menu item that extends to those component menu entries. That special menu item can not filter by specific components or menu entries. So long story short: You have ways to add your components content to the dashboard, but not really individually to the menus. But I would argue that we have the custom backend menus for that.

Does that "solve" this issue for you?

**Comment by brianteeman** [comment]
That makes the new feature useless for me :(

**Comment by brianteeman** [comment]
I know I am obviously beating a dead horse but this is another example of why CODE should not have been introduced here in this template but should have been in the main repo

**Comment by brianteeman** [comment]
Seriously it makes the whole point of moving core components to the system menu because they are "system functions" not "content functions" a complete waste of time if a component that also performs "system functions" has to live in the component menu with the other "content functions".

**Comment by Hackwar** [comment]
First of all: No, this template project isn't just changing a bunch of CSS files. The team has tried its best to make all changes that could be done in the main repo a PR exactly there. However there are several changes that interlock, which either can not be done in a PR for the main repo or would live in eternal limbo and thus block further development. So, this sub-project is fine doing code changes and will keep on doing so.

Regarding this specific issue: Yes, the feature isn't perfect, but you are very welcome to provide a better solution. The current implementation uses as much existing features as possible, while cleaning up the code at the same time. This btw is an example of a feature that has been done (partially) via the main repo: https://github.com/joomla/joomla-cms/pull/23452

If you have want to propose a better implementation, please open a PR. For now I will close this issue.

**Comment by brianteeman** [comment]
This working practice is wasting everyones time and you are just delaying the pain of seeing the entire sub-project being rejected at review because it is not fit for purpose. 

Closing issues doesnt resolve problems.

**Comment by Hackwar** [comment]
You wanting an additional feature is not a problem. It is a feature request and as I told you above, you are free to provide a better solution than what we have right now. But right now, this exceeds the timeframe and capabilities of this team and thus is out of scope.

**Comment by brianteeman** [comment]
Feature request, Issue or Bug - your arbitrary decision that you dont have time to do it is no reason to close a valid issue

**Comment by brianteeman** [comment]
Looking into the code and I can see that you already have a Todo to address this via plugins
https://github.com/joomla/backend-template/blob/745912f46595489b84f46ba79598b1931a05a6f5/administrator/components/com_cpanel/Model/SystemModel.php#L239

I was thinking that we could add a new optional param to the component xml file to indicate that it is to be included in the system menu not the components menu and then update the code in the mod_submenu to exclude those components and add them to the hardcoded dashboard

**Comment by Hackwar** [comment]
This is a temporary project and more or less the moment that this is merged into the main repo, this project will be archived and quite frankly no one will ever have a look at it again. If we can not get this done in time, then keeping a Feature Request open will have no use for you. Open it up in the main repo and you have a chance to actually see it realised. 

Call it an arbitrary decision, but I'm making it here.

Regarding your proposal: That file is not used anymore, was deleted and seems to have crept back in with some of the merges from the main repo. The menu items on the dashboard are still either custom backend menus, like we have them in 3.x or they are an XML file. There are plugin events to add your own stuff, but that is quite frankly nothing that any component dev will ever use to add entries the way you want to do it.

**Comment by brianteeman** [comment]
Until this repo is closed it should remain open. You never know someone might miraculously see it and realise that they have a solution. They never will if you just dismiss it.  

As stated before as it is right now the system dashboard is completely useless if you can not add new system "stuff" to it and should be rejected.
