### ISSUE TITLE
Closing alerts

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#266]
### Steps to reproduce the issue
Do something that will generate more than 1 alert
For example select more than one menu item and select "default" from the actions dropdown

### Expected result
Two alerts each of which has an X to close

### Actual result
See movie

![message](https://user-images.githubusercontent.com/1296369/58439315-5ee08680-80cb-11e9-9a7a-07582168a485.gif)

**Comment by astridx** [comment]
I have just cloned this repo. I can not confirm this issue. But: I'm unsure. I am on the 4.0-dev branch. Everything looks different to me, especially the buttons. Am I on the right branch?
![Menus  Items  Main Menu    backend test   Administration](https://user-images.githubusercontent.com/9974686/58834829-9bc0f600-8654-11e9-9d5c-ef2e39e4b617.png)

**Comment by brianteeman** [comment]
You need to be on the "releases" branch

**Comment by astridx** [comment]
@brianteeman Thank you very much for your quick response. On the branch release I can confirm the issue.
![Menus  Items  Main Menu    Test   Administration](https://user-images.githubusercontent.com/9974686/58835669-df1c6400-8656-11e9-830f-aafa1573f804.png)

**Comment by nadjak77** [comment]
fixed in PR [#282](https://github.com/joomla/backend-template/pull/282)

**Comment by bembelimen** [comment]
Closed as we have a PR
