### ISSUE TITLE
Well layout produces invalid html

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#271]
https://github.com/joomla/backend-template/blob/745912f46595489b84f46ba79598b1931a05a6f5/administrator/templates/atum/html/layouts/chromes/well.php#L74

If there is no $headerClass then you get an empty class in the markup

`<h2 class=""><span class="fa fa-desktop mr-2" aria-hidden="true"></span>Site</h2>
`

**Comment by chmst** [comment]
Fixed in PR #270
