### ISSUE TITLE
Implementation of alerts

### ISSUE THREAD

**Issue by chmst** [joomla/backend-template#28]
### What needs to be fixed
At the moment alerts have a headline which is defined as h4. But Heading levels should only increase by one. (AXE)

### Why this should be fixed
Wrong structure of headlines is bad for SEO and and is a11y issue

### How would you fix it
Use a CSS class (alert-heading) for formatting the headlines of alerts:   not a < h4 >   tag

### Side Effects expected
Note: Alerts are not always generated by media/js/system/core.js., but sometimes in layouts.

**Comment by chmst** [comment]
Out of scope, closed

**Comment by chmst** [comment]
If we can resolve this, it wold be grat, so reopened

**Comment by bembelimen** [comment]
@coolcat-creations rebuilt the Alerts here https://github.com/joomla/backend-template/commit/0d025f0cf11fae652c67abaaa5b898d157b83656, I think more should be done in the Core, not here.
