### ISSUE TITLE
New list filters

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#283]
I like the implementation of the list filters opening horizontally instead of vertically. It would be even better if when a filter is set then the list remains open until all filters have been removed. Currently its very distracting that as soon as you click anywhere the filters disappear. 

![filters](https://user-images.githubusercontent.com/1296369/59021446-b907e700-8843-11e9-94ab-08c2ca4c1aec.gif)

I guess that if the list of filters is always open when there is a filter selected then we dont need the count anymore?

**Comment by bembelimen** [comment]
Good suggestions, I like.

**Comment by brianteeman** [comment]
Oh wait - isn't that the tried and tested solution we have in joomla3 ;)

The wheels are round. Changing them doesn't make them any rounder
</sarcasm>

**Comment by bembelimen** [comment]
Thx. https://github.com/joomla/backend-template/pull/331
