### ISSUE TITLE
! layouts overrides missing !

### ISSUE THREAD

**Issue by infograf768** [joomla/backend-template#297]
As title says... in the release branch

1. layouts folder totally missing in com_associations

2. `/administrator/components/com_menus/layouts/joomla/searchtools/default.php`
missing for com_menus

Whats happening here?
This breaks the filters for these components.

**Comment by infograf768** [comment]
And they should be modified to fit the new design.

**Comment by infograf768** [comment]
Once added these layouts override files, if I undo a change in 
`backend-template-release/administrator/templates/atum/scss/blocks/_searchtools.scss`

Top of file changing back to:
```
.js-stools {
  position: relative;
  display: flex;
  justify-content: flex-end;
  padding: 5px 0 0;
```
instead of
```
.js-stools {
  position: relative;
  padding: 5px 0 0;
```

I get back the correct display for the menu items manager and com_associations Manager filters:
![Screen Shot 2019-06-21 at 09 32 35](https://user-images.githubusercontent.com/869724/59905907-ad9de980-9407-11e9-98f0-9ea1970d15b8.png)

![Screen Shot 2019-06-21 at 09 30 31](https://user-images.githubusercontent.com/869724/59905921-b2fb3400-9407-11e9-84f3-5c1e0867ec40.png)

Note: _Almost_ the correct display as the Manager title is cut off...

Alas, this modification breaks the Filter Options display... 
![Screen Shot 2019-06-21 at 09 39 20](https://user-images.githubusercontent.com/869724/59906235-83006080-9408-11e9-9fd9-4983dad4839a.png)

**Comment by infograf768** [comment]
@coolcat-creations

**Comment by coolcat-creations** [comment]
Hi! I am currently not in the team.

**Comment by infograf768** [comment]
Sorry.
Indeed I should have pinged @ciar4n and @bembelimen I guess as the whole search tools stuff is in real bad shape. 

Even the Clear button which does not clear the Search field anymore if nothing is selected in the Filter Options as it is disabled in that case by the js
https://github.com/joomla/backend-template/blob/31f65d5658a25153cc563127cfd1bf800e8439b7/build/media_source/system/js/searchtools.es6.js#L306-L308

this was modified in 
https://github.com/joomla/backend-template/commit/31f65d5658a25153cc563127cfd1bf800e8439b7#diff-3ad6d95bcfe59433973d65ae0df94113

by @elmar

**Comment by infograf768** [comment]
I can add the missing layouts and adapt them to this new admintemplate as well as correct the js and modify slightly the searchtools css to cope with managers using 2 filters separated from the Fiter Options.
The enormous size of these filters should anyway be modified imho as they need a lot of real estate.
I think it is unecessary to display the text and their containers in the same size as the Toolbar.

**Comment by bembelimen** [comment]
Hello @infograf768 thank you for the report, the searchtools are WIP at the moment, to have it normalized we removed the old overrides and will readd them, when the searchtools are reworked.

**Comment by bembelimen** [comment]
See: https://github.com/joomla/backend-template/pull/342

Thx.
