### ISSUE TITLE
I could not open the System menu.

### ISSUE THREAD

**Issue by astridx** [joomla/backend-template#298]
I just synced the release branch. Then I ran `composer i` and `npm i `and did a new installation.
Actually, I wanted to install an extension and see how everything looks in the new template.
I could not open the System menu. See image. Am I doing something wrong?

![Error  0](https://user-images.githubusercontent.com/9974686/59876082-e35cb700-93a2-11e9-95c4-761bed409935.png)
And this looks wrong to me.
![Control Panel   test   Administration(1)](https://user-images.githubusercontent.com/9974686/59876081-e35cb700-93a2-11e9-8480-3027809ca77c.png)

**Comment by chmst** [comment]
The second will be comitted now.
The first - missing class is strange. Could you try to delete the file libraires/autoload_psr4.php?

**Comment by astridx** [comment]
Many Thanks @chmst . Deleting the file solved the first problem. The second continues with me.

**Comment by chmst** [comment]
The second comes from a fresh installation, where the size of the cache is not initialised. I'll make te patch  asap.

**Comment by bembelimen** [comment]
Closing as we have a PR
