### ISSUE TITLE
Page-Heading is hidden

### ISSUE THREAD

**Issue by Hackwar** [joomla/backend-template#30]
Currently the heading of a backend page is right next to the upper left corner logo. In that position at least for me the heading is invisible. I simply don't notice it as part of the current page, but just as an artifact like the menu.

To our designers: Please consider how we could make it more prominent, for example by moving it over to the right a bit so that it is in the same column as the actual component output. (So right from the sidebar...)

How should this behave in mobile?

**Comment by coolcat-creations** [comment]
@Hackwar is it better now for you ? May I close?

**Comment by Hackwar** [comment]
This is done. Closing.
