### ISSUE TITLE
Help Icon is to small

### ISSUE THREAD

**Issue by astridx** [joomla/backend-template#300]
Help Icon is to small - see picture:
![Menus  All Menu Items   test   Administration](https://user-images.githubusercontent.com/9974686/60050057-fbe50e00-96cf-11e9-9f18-83196a2af846.png)

**Comment by brianteeman** [comment]
I assumed that the change on these buttons was a mistake as they are completely inaccessible

**Comment by brianteeman** [comment]
Should be resolved now by #311

**Comment by bembelimen** [comment]
Thx.
