### ISSUE TITLE
Borders in create menu item

### ISSUE THREAD

**Issue by astridx** [joomla/backend-template#302]
Here the frames are not flush:
![Menus  New Item   test   Administration(1)](https://user-images.githubusercontent.com/9974686/60077537-7b9fc680-972a-11e9-8299-a4842bf9e689.png)
Maybe that's what you want. But: I'm bothered that here is no left frame:
![Menus  New Item   test   Administration](https://user-images.githubusercontent.com/9974686/60077538-7c385d00-972a-11e9-93a0-f393a14cc680.png)

**Comment by bembelimen** [comment]
Please check this PR: 
https://github.com/joomla/backend-template/pull/252

**Comment by bembelimen** [comment]
Should be fixed in the system + by the PR.
