### ISSUE TITLE
Space between buttons

### ISSUE THREAD

**Issue by astridx** [joomla/backend-template#303]
On my notebook (1366 width) there is no space between the buttons in the toolbar. 

![Menus  Items  Main Menu    test   Administration](https://user-images.githubusercontent.com/9974686/60078539-69268c80-972c-11e9-8da0-d3b618ced997.png)

If I make the screen a little smaller, a gap appears. 

![Menus  Items  Main Menu    test   Administration(1)](https://user-images.githubusercontent.com/9974686/60078537-688df600-972c-11e9-8bdc-dd237fa4c05e.png)

I would find it nice if the gap is always present if the buttons do not fit in a row.

**Comment by bembelimen** [comment]
Fixed with: https://github.com/joomla/backend-template/pull/342
