### ISSUE TITLE
Tabs at the bottom (invisible on windows) - release blocker

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#306]
Using windows 10 the toolbar at the bottom is set to either fixed display or automatically hidden. 

When it is set to fixed display then the new tab bar is visible

![image](https://user-images.githubusercontent.com/1296369/60128269-23001600-978a-11e9-94cf-0221deae7ee0.png)

When it is set to automatically hidden then the new tab bar is visible

![image](https://user-images.githubusercontent.com/1296369/60128312-4034e480-978a-11e9-98ac-cdef80d3b39d.png)

UNLESS there is a notification on the toolbar which forces it open. This is very common (for me at least) and I often dont check that notification until later in the day. But look what happens to the tab bar now

![image](https://user-images.githubusercontent.com/1296369/60128402-783c2780-978a-11e9-82ca-bca2b815facf.png)

Even if you know that the tab bar exists it is never possible to scroll to it

**Comment by HLeithner** [comment]
That's out of scope of any website because it's outside the Webbrowser and can't be fixed.

**Comment by brianteeman** [comment]
Which is why havIng critical parts of the ui completely obscured is a release blocker

**Comment by HLeithner** [comment]
why are you hiding the program you want to use? The same "problem" (btw. that's intended behavior by Microsoft)  is true for every other Software you use.

You can say the same if you open another window lay it over your browser and says I can't see the webpage it's your fault.

**Comment by brianteeman** [comment]
My desktop right now. No idea which of those apps is causing the bar to stay open. Dont care and neither should I. I will get to it when I get to it. Right now I just want to create content. I wouldnt even know there was anything behind that blue bar. I dont even know that it is above anything important as no other app that i have open has critical elements of the ui obscured


![image](https://user-images.githubusercontent.com/1296369/60191496-52fff580-982c-11e9-9d02-9be1ce3d7ff9.png)

**Comment by HLeithner** [comment]
The please fix your taskbar or don't use fullscreen. Problem solved.

**Comment by brianteeman** [comment]
![you-can-not-be-serious-the-bar-is-behind-the-line](https://user-images.githubusercontent.com/1296369/60192071-3a440f80-982d-11e9-8b52-fa3be1a27834.jpg)

How would someone know that there is something hidden behind the bar!!!

**Comment by HLeithner** [comment]
But your are right I have the same problem.
![image](https://user-images.githubusercontent.com/1497730/60192315-f0135c00-9835-11e9-8576-55d7bbeb48f2.png)

**Comment by ciar4n** [comment]
Personally never a fan of this idea of moving tabs to the footer. It's a common idea for touch screen devices as it gives easy access to the thumb finger, for a desktop UI however, the footer is usually reserved for either the least used actions or in the odd occasion for the last used action (eg. save, close etc.). Tabs, in my opinion, is neither.

**Comment by brianteeman** [comment]
It makes sense on mobile but not on desktop

**Comment by Hackwar** [comment]
Please have a look at #366

**Comment by brianteeman** [comment]
Thank you for listening
