### ISSUE TITLE
Keyboard/screenreader navigation with the new filter options

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#310]
When you tab to the filter options and then hit enter you open the area with the filters. The expected behaviour is that you can then select your filters. But before you can do that you have to navigate past the sort options.

It is true that this is not any extra keystrokes compared to the current dropdown filter select but it is not a logical order. A screen reader would also be confused by this.

### This repo
![filter](https://user-images.githubusercontent.com/1296369/60203310-4edfd200-9844-11e9-81b6-c0dda475dc95.gif)

### Original repo
![goodfilter](https://user-images.githubusercontent.com/1296369/60203494-a67e3d80-9844-11e9-960c-18d30b4e8050.gif)

**Comment by brianteeman** [comment]
Last night I had this reviewed and confirmed by the drupal core accessibility maintainer

**Comment by chmst** [comment]
Maybe I miss something? I don't see the issue. If I want to filter a big amount of data, I first say the ordering and the limit, then I can activate the filter. Activating a filter is a inClick event, I must define ordering and list limit before.

**Comment by brianteeman** [comment]
https://github.com/joomla/backend-template/issues/309#issuecomment-506301499

**Comment by brianteeman** [comment]
Try doing that with a keyboard. You would go to the ordering. then back to open the filter. then passed the ordering again to get to the filters

**Comment by brianteeman** [comment]
Also remember you might not be filtering just because there is a large number of items. If you filter to select a specific category and then click NEW the category will be preselected.

**Comment by chmst** [comment]
thx, there are many ways ..

**Comment by micker** [comment]
hello just to understand no way to see this feature in j4 ?
