### ISSUE TITLE
Tooltip and submenu in com_contact

### ISSUE THREAD

**Issue by astridx** [joomla/backend-template#317]
![Contacts   test   Administration(1)](https://user-images.githubusercontent.com/9974686/60450763-d8b7e280-9c2a-11e9-97cd-6498c806678f.png)
Tool-tip and sub menu in com_contact is not like in com_content.
The Tool-tip is to small and the sub menu should be in the left sidebar in my opinion.

**Comment by brianteeman** [comment]
Tooltip is already resolved and merged in Joomla as it is nothign to do with the template
Sidebar is already resolved and waiting tests and conflict fixes in Joomla #23366

**Comment by astridx** [comment]
@brianteeman Thanks for explaining.
