### ISSUE TITLE
List-Filters need to be better accessible

### ISSUE THREAD

**Issue by Hackwar** [joomla/backend-template#32]
The current filters above the list views are unfortunately not very userfriendly. They require the knowledge that there is such a filter behind that button and it requires additional clicks and does not show selected filters when the page has reloaded. We have to find a better solution to display this. The filters of 3.x aren't great, but right now I'd rather go back to those and style them a bit than to stay with that current dropdown.

**Comment by coolcat-creations** [comment]
https://github.com/joomla/backend-template/issues/66
https://github.com/joomla/backend-template/issues/67

**Comment by Hackwar** [comment]
We have a PR (#185) Closing this one.
