### ISSUE TITLE
Main repo css changes

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#321]
Have you been applying changes made in the main repo css to this one?

If you look at the position of the text "Featured" in this screenshot. Thats something I fixed ages ago in the main repo. 

![image](https://user-images.githubusercontent.com/1296369/60523182-34917280-9ce2-11e9-98c5-5de1476d99e7.png)

**Comment by wilsonge** [comment]
https://github.com/joomla/backend-template/pull/329 

Looks like that one got lost in conflicts. The one JM did however did get ported so 🤷‍♂ . always the risk with conflicts :(

**Comment by brianteeman** [comment]
I was more concerned that someone hadn't said - oh we're replacingthe template we can just ignore changes there
