### ISSUE TITLE
Install icon

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#322]
The icon used is called "cloud-download-alt" so clearly it is being used for the opposite of what install is supposed to be. Remember other people uses these icons. In fact the site I am working on right now uses that same icon for download. 

I would suggest using the upload icon https://fontawesome.com/icons?d=gallery&q=upload&m=free

![image](https://user-images.githubusercontent.com/1296369/60523916-85ee3180-9ce3-11e9-98a7-0dcc4e93df67.png)

**Comment by bembelimen** [comment]
Thx https://github.com/joomla/backend-template/pull/323
