### ISSUE TITLE
Clear button no longer works as intended

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#325]
The fix for #240 is only a partial fix. 

The clear button will now clear the search field and the filters **but** the clear button is a disabled button unless there are any filters selected.

So if you have 0 filters set and a search term then you can't clear the search term as the button is disabled

**Comment by bembelimen** [comment]
Hi,

this line should technically fix it: https://github.com/joomla/backend-template/blob/release/build/media_source/system/js/searchtools.es6.js#L301
The button only becomes disabled if no filter is selected and no search term is set.

**Comment by brianteeman** [comment]
My bad - I thought my branch was up to date - it wasnt
