### ISSUE TITLE
jdoc code style

### ISSUE THREAD

**Issue by bembelimen** [joomla/backend-template#327]
Not sure if we have anything in the codestyle docs on this but everywhere else it seems to be 
`<jdoc:include ........" />`

_Originally posted by @brianteeman in https://github.com/joomla/backend-template/pull/294_

**Comment by brianteeman** [comment]
Sorry didnt see you assigned it to someone - I submitted a PR #328

**Comment by bembelimen** [comment]
https://github.com/joomla/backend-template/pull/328 thx
