### ISSUE TITLE
tabs on the bottom - mobile view

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#339]
### Steps to reproduce the issue
on a mobile device - not a reduced screensize, open a page such as the create new article form

### Expected result
the tabs (i complain about) will display at the bottom of the screen

### Actual result
You can see about 2pixels of the top of tab - the rest is obscured by the bottom menu thing

![image](https://user-images.githubusercontent.com/1296369/60721009-71e54280-9f24-11e9-93b0-3e5b5f1e6fcc.png)

### System information (as much as possible)
Tested on Android 8, Android 9

**Comment by Hackwar** [comment]
I've changed the tabs a bit in another PR, but in general they are now displayed as an accordion. They still seem to have issues, but this issue I can't replicate anymore. Can you check that again?

**Comment by brianteeman** [comment]
Thank you. Accordion resolves this
