### ISSUE TITLE
footer-mobil-icon

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#340]
I spotted this class and as the english is mobile I thought I would fix it. But although I can see it being used I cant see it being declared - or I am missing something which is entirely possible

https://github.com/joomla/backend-template/blob/763bc9235b26443e49440e24f2f02315806ee5a6/administrator/modules/mod_status_frontend/tmpl/default.php#L27

https://github.com/joomla/backend-template/blob/763bc9235b26443e49440e24f2f02315806ee5a6/administrator/modules/mod_status_user/tmpl/default.php#L26

https://github.com/joomla/backend-template/blob/763bc9235b26443e49440e24f2f02315806ee5a6/build/media_source/templates/atum/js/template.es6.js#L163

**Comment by brianteeman** [comment]
I can see it in the core.js as well

**Comment by bembelimen** [comment]
No it does not seem to be used anymore.

**Comment by brianteeman** [comment]
closed see #372
