### ISSUE TITLE
No matching results - duplicated

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#344]
### Steps to reproduce the issue
In the menu manager do a silly filter that will produce no results

### Expected result
A single message "no matching results"

### Actual result
You get the message twice
![image](https://user-images.githubusercontent.com/1296369/60743253-b1ce1900-9f68-11e9-8e60-e8601c228b5f.png)

### Additional comments
This is fine in the main repo
I tested com_content and it didnt happen there

**Comment by brianteeman** [comment]
found the problem - PR incoming I hope

**Comment by brianteeman** [comment]
sorry - no idea why this is happening in this repo and not in the main repo

I can say that one message is coming from 
https://github.com/joomla/backend-template/blob/f0d19edf2580e11aaf713d5449452ef87e89c9de/administrator/components/com_menus/forms/filter_items.xml#L30
and one message from
https://github.com/joomla/backend-template/blob/f0d19edf2580e11aaf713d5449452ef87e89c9de/administrator/components/com_menus/tmpl/items/default.php#L48-L51

**Comment by bembelimen** [comment]
Yes, the search layout outputs the message if https://github.com/joomla/backend-template/blob/release/administrator/components/com_menus/forms/filter_items.xml#L30 is set.
So no need for https://github.com/joomla/backend-template/blob/release/administrator/components/com_menus/tmpl/items/default.php#L49-L52

(So the XML for every list view should be updated and the message removed from the tmpl layout)

**Comment by bembelimen** [comment]
I created a PR. Thx.
