### ISSUE TITLE
monochrome

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#348]
monochrome only partially works as large parts are still in color. I am _guessing_ that its because those elements still in color have a real color defined in the css and not a variable.

if thats correct then its going to be a lot of work for someone to go through all the css and change the colors to vars and that wont work for extensions

If my understanding is correct then you can look at some js to do this. I had hoped to use an accessibility javascript and one of its options was to make everything gray. It works by using filters (i think) . Anyway it works. Maybe you can borrow that js and use it instead of this complex php that doesnt look like it can ever work 100%

https://github.com/joomla/joomla-cms/pull/24112

**Comment by brianteeman** [comment]
BTW the only reason we havent merged the accessibility script was because it has no persistance across pages and upstream is not responding. @wilsonge and I agreed we will probably fork the plugin but it wasnt urgent. I dont think either of us realised you could possibly use it here

**Comment by nadjak77** [comment]
The colors like "success" or "danger"... should be still in color. I think they are "important" to see, so they stay in color.
But you are right, there were some colors who should change to monochrome. I changed the definition so they change now.
You can see it in the branch[ tmp_colorhelper.](https://github.com/joomla/backend-template/tree/tmp_colorhelper)

**Comment by brianteeman** [comment]
Maybe your concept of the reason for this are very different to mine

**Comment by nadjak77** [comment]
Could you please explain a bit more where you see the problems? Thanks

**Comment by brianteeman** [comment]
If I chose an option called monochrome then I would expect everything to be monochrome.

<img width="1174" alt="chrome_2019-07-07_13-20-56" src="https://user-images.githubusercontent.com/1296369/60768210-53b14b00-a0ba-11e9-9bad-4ada18dba842.png">

<img width="1278" alt="chrome_2019-07-07_13-21-25" src="https://user-images.githubusercontent.com/1296369/60768213-5f047680-a0ba-11e9-99f6-670f751ab744.png">

<img width="1274" alt="chrome_2019-07-07_13-21-50" src="https://user-images.githubusercontent.com/1296369/60768214-5f9d0d00-a0ba-11e9-9abe-3bc9fd7ed33c.png">

**Comment by zwiastunsw** [comment]
@nadjak77 write:
> The colors like "success" or "danger"... should be still in color. I think they are "important" to see, so they stay in color.

That's the wrong approach! Monochromatic colours are for people who have difficulty distinguishing colours (colour blindness). If you have a monochrome version, it has to be a full monochrome version.
In general, the weighting of a message only in colour is not accessible. Another visual indicator must be used, e.g. an icon.

**Comment by brianteeman** [comment]
This can be closed as it has been correctly resolved
