### ISSUE TITLE
Save Content Buttons

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#36]
Now Save looks like this:
![grafik](https://user-images.githubusercontent.com/828371/52114877-8176fd00-260d-11e9-870b-ff5c1ac1b3d6.png)

It should look like this:
![grafik](https://user-images.githubusercontent.com/828371/52114927-9a7fae00-260d-11e9-9124-930018a7efc3.png)

**Comment by bembelimen** [comment]
@lavipr could you please add the correct icon (as mentioned here: #128 the icon was not updated)

**Comment by lavipr** [comment]
Fixed with 5aa2d07

**Comment by coolcat-creations** [comment]
Closed as done :) thank you @lavipr
