### ISSUE TITLE
Remove vendor prefixes from SCSS

### ISSUE THREAD

**Issue by C-Lodder** [joomla/backend-template#369]
My comments on previous PRs were ignored so I'll submit an issue for this.

Vendor prefixes can be removed from all SCSS files as this is dealt with automatically by the `autoprefixer` package.

You can also replace `not ie < 11` with `not ie 11` in this file: https://github.com/joomla/backend-template/blob/release/build/build-modules-js/settings.json#L5

**Comment by bembelimen** [comment]
Hi @C-Lodder sorry, it was not my intention to ignore you in any way, I guess I just missed it. Could you please link me to your comment?

**Comment by C-Lodder** [comment]
I cant be bothered to sift through PR's for a comment. That fact still stands and vendor prefixes simply need to removed
