### ISSUE TITLE
Make values selectable from manage list

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#37]
### Is your feature request related to a problem? Please describe.
If you want to change the ACL from a List item (article, Category, LAnguage) you have to click into the item itself, change and close it. In Joomla 1.5 it was possible to change it from the manage view.

You click on "public" and a dropdown appears where you can change the access. Same would be good for language and maybe title.

![grafik](https://user-images.githubusercontent.com/828371/52220299-cebdcd80-289e-11e9-9651-b34f088ba437.png)

**Comment by bembelimen** [comment]
Not out task => do in core
