### ISSUE TITLE
Com-tags

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#377]
Was it the intention to have Teaser Image and Full Image on seperate tabs ?

![image](https://user-images.githubusercontent.com/1296369/61119553-00ad0e80-a493-11e9-8c17-76bcdfc7e812.png)

If it was then this scss is wrong - but I suspect you meant it to be one tab

```
	#fieldset-image-intro {
		margin-right: 15px;
	}
	#fieldset-image-fulltext {
		margin-left: 15px;
	}
```

**Comment by bembelimen** [comment]
Indeed. #382
