### ISSUE TITLE
Switcher

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#378]
### Steps to reproduce the issue
example page 
administrator/index.php?option=com_fields&view=field&layout=edit&context=com_users.user

### Expected result
![image](https://user-images.githubusercontent.com/1296369/61120140-2f77b480-a494-11e9-9019-d149847a9fca.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/61120117-21299880-a494-11e9-9884-6224808bf30d.png)

### Additional comments
This is caused by 
![image](https://user-images.githubusercontent.com/1296369/61120184-43bbb180-a494-11e9-87ba-1924e542cc89.png)

The code can be found in `administrator\templates\atum\scss\blocks\_edit.scss _edit.css`

```
.layout-edit {
	.control-group {
		min-width: (100% / 3);
	}
	.control-label {
		float: none;
		width: 100%;
	}
	.controls {
		margin-left: 0;
	}
	.switcher__legend {
		margin-left: 0;
		float: none;
	}

```

I didn't fix this myself as I am unsure if you did this to address something specific and I just found an unintentional consequence or if its simply a bug

**Comment by bembelimen** [comment]
The whole switcher thing has a more "generic" problem.
Joomla! gives all labels 220px margin-left. Therefore we have to set ```margin-left: -220px``` for the switcher, in some cases and ```0``` in some other cases (depending if label + field are in one line or not). So at the moment we have to visit every switcher and decide, what we have to set.

A better solution would be:
1. use the bootstrap 4 classes
or (to be independent)
2. Handle all this margin stuff by using a "generic" class in the parent element like "form-horizontal" or "form-vertical".

Default should be vertical I guess.

**Comment by brianteeman** [comment]
1. yeah I know about the 220px - I wrote the code for the switcher :)
2. it was based on the form vertical and form horizontal iirc
3. When outputting the legend above the field we will also have to remove the legend width of 220px to avoid this
![image](https://user-images.githubusercontent.com/1296369/61158358-9c209c80-a4f0-11e9-8735-8b419ea2eb19.png)

**Comment by bembelimen** [comment]
I think the solution is "easier" than expected.

We have to remove all this "customizing" from the template itself and let the switcher do its -220px magic. But if we want to remove it (= labels are over the input) we just have to set [```.form-no-margin```](https://github.com/joomla/backend-template/blob/release/administrator/templates/atum/scss/blocks/_form.scss#L40) to one of the parent elements.

**Comment by brianteeman** [comment]
I did say before that the switcher css should not be "customised" in the template :)

**Comment by ciar4n** [comment]
Before adding further to this CSS, it should be changed to flex. The current `control-group` CSS is very dated (IE10?). Flex resolves a lot of these issues out of the box.... its a perfect use case for flex... less CSS... not a hack (currently floating a label to remove from page flow and then adding a left margin to inline field... its weird).

**Comment by bembelimen** [comment]
I think, the switcher has a few issues especially regarding this ```.col-md-9 .switcher__legend, .col-md-12 .switcher__legend``` code. But I removed most of the CSS code from the template, regarding the switcher.

I agree with @ciar4n about becoming flex, but I think this should be done in the core repo, because it's much more than the edit screens.

**Comment by brianteeman** [comment]
Closed as resolved for now
