### ISSUE TITLE
Control Panel Boxes

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#38]
Boxes come from two sides: mod_quickicon and plugins

Rewrite mod_quickicons/Helper, layout quickicons(/icon.php, language file mod_quickicons
- [x] Icon Users, Menu Items, Articles, Categories as in the design is present 
- [x] Icons show number of published Items - regardless of permissions or structures
- [x] Adapt language file
- [x] Style classes for quickicons 
- [x] Make sure that there is no b/c break
- [x] a11y 

3 from plugins for maintaining the system

On COntrolpanel the boxes at the top:

![grafik](https://user-images.githubusercontent.com/828371/52238110-8537a780-28cb-11e9-8574-ea8016f042f9.png)

should look like this:

![grafik](https://user-images.githubusercontent.com/828371/52238169-ad270b00-28cb-11e9-9c80-ad97a7b25831.png)

after 6 Panels, break and create a second row if needed.

For Example 6 or 4/4 etc....

**Comment by chmst** [comment]
Close as the design has changed.
