### ISSUE TITLE
'class for service key 'atum' does not exist'

### ISSUE THREAD

**Issue by ciar4n** [joomla/backend-template#386]
```Error: The 'Joomla\Template\Atum\Administrator\Service\HTML\Atum' class for service key 'atum' does not exist.: The 'Joomla\Template\Atum\Administrator\Service\HTML\Atum' class for service key 'atum' does not exist.```

Getting the above on a fresh install accessing /administrator. Frontend loading fine.

**Comment by Hackwar** [comment]
Please delete your libraries/autoload_psr4.phpAm 13.07.2019 10:49 schrieb Ciaran Walsh <notifications@github.com>:Error: The 'Joomla\Template\Atum\Administrator\Service\HTML\Atum' class for service key 'atum' does not exist.: The 'Joomla\Template\Atum\Administrator\Service\HTML\Atum' class for service key 'atum' does not exist.
Getting the above on a fresh install accessing /administrator. Frontend loading fine.
