### ISSUE TITLE
Language installation

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#40]
From this point:
![grafik](https://user-images.githubusercontent.com/828371/52255900-bd170d00-2914-11e9-8aa4-877da2668f27.png)

I should be able to access content languages immediately since it's the next step to implement the language. We need to have all the Manage Options in the left Menu.

![grafik](https://user-images.githubusercontent.com/828371/52255946-f8b1d700-2914-11e9-9ec0-f013379300a7.png)

**Comment by bembelimen** [comment]
Should be done in the core.
