### ISSUE TITLE
System Settings Dashboard

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#5]
@chmst - Can you convert this to an interactive dashboard, in which the user also gets important information as option?

@svom please optimise this view also add "Clear Cache Button"

Migrated issue from: https://github.com/joomla/40-backend-template/issues/430

1) Interactive Dashboard for the System Settings, things to pay attention to should be obvious, things that are not needed should be marked as well (maybe lowe opacity if cache is absolutely empty, so user does not have to click inside to see it's noting there)
![settings - initial](https://user-images.githubusercontent.com/828371/40283391-acc040a2-5c7d-11e8-830b-ce4e672bd2e6.png)

2) Mobile example
![mobile](https://user-images.githubusercontent.com/828371/40283393-b113d736-5c7d-11e8-81af-8261fa72ff32.png)

**Comment by coolcat-creations** [comment]
@bembelimen @Hackwar is it still possible to add at least a checkin or clear cache button in this view? If no, feel free to close the issue :)

**Comment by Hackwar** [comment]
The grunt of the work has been done and thus I'm closing this Issue.
