### ISSUE TITLE
Login as user without backend access - sliding effect

### ISSUE THREAD

**Issue by chmst** [joomla/backend-template#70]
Create a user in a group without backend access. Try to login with this account.

### Expected result
An Error message as for example "do not have access to the Administrator section of this site"
or nothing.

### Actual result
The error message is displayed but disappears then in a sliding effect.

**Comment by chmst** [comment]
The sliding effect is now all right. 
But if the user repeats login with wrong data, the screen jumps. It seems as if a second warning is display after the first warning before the old warning is removed.

**Comment by coolcat-creations** [comment]
@chmst - can you test again I can't reproduct the issue :)

**Comment by chmst** [comment]
On Firefox and Edge (win10)
Let both input empty and  click log on. You get an error message (alert)
Click on log on again - the screen jumps
