### ISSUE TITLE
Add context sensitive help where it is needed

### ISSUE THREAD

**Issue by chmst** [joomla/backend-template#8]
### Steps to reproduce the issue
https://github.com/joomla/joomla-cms/pull/22165  this PR removed tooltips from configuration because tooltips as they are now in v 3.x are not accessible.

### Expected result
The system delivers context sensitive help in a form which is accessoble for all and works on smlall devieces as well

For accessible context sensitive help, we have several possibilies. 
One of them is adding a help-button to elements. 

Where this is not possible, we must find another solution. 

@svom @coolcat-creations the design should be made with buttons for context-sensitive help where this is possible. If it is not possible we have to discuss a solution

**Comment by coolcat-creations** [comment]
Can we merge this? https://github.com/joomla/joomla-cms/pull/18452 or is it not a11y ?

**Comment by bembelimen** [comment]
I think, this should be solved in the core.
