### ISSUE TITLE
Links in Texts must be recognizable as links

### ISSUE THREAD

**Issue by chmst** [joomla/backend-template#9]
### Steps to reproduce the issue
See this view:
/administrator/index.php?option=com_postinstall
The text contains links. These links are not  recognizable as links for colorblind people. 

### Expected result
The link is recognizable as a link. Underlining is the usual method. 
Font-weight bold is possible but could  be in conflict with simple < strong >
A good solutionis an icon, added per css :after 

### Actual result
These links are not  recognizable as links also for colorblind people. 

@coolcat-creations, @svom - please decide how a link can be styled
@nadjak77 this will be a default for text-links

**Comment by bembelimen** [comment]
Is implemented.
