### ISSUE TITLE
Massive performance hit

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#95]
I was trying to work out why my install from this repo was so much slower than the main repo. With debug turned on I found the reason - at least for the first page

### Main repo
**Queries**
43 statements were executed, 2 of which were duplicates, 41 unique
**Request Duration**
79.43ms
**Profile of mod_menu**
beforeRenderModule mod_quickicon (Quick Icons) (1.23MB) (31.88ms)
afterRenderModule mod_quickicon (Quick Icons) (267.64KB) (26.63ms)

### This repo
**Queries**
150 statements were executed, 37 of which were duplicates, 113 unique
**Request Duration**
2.95s
**Profile of mod_quickicon**
beforeRenderModule mod_quickicon (Quick Icons) (1.37MB) (225.14ms)
afterRenderModule mod_quickicon (Quick Icons) (3.21MB) (1.6s)

**Comment by bembelimen** [comment]
Hello Brian,

thank you for your feedback. We notices this issue, too :( but we're working on a solution at the moment.

**Comment by brianteeman** [comment]
It's hard to tell if anything is a known issue as there is so little activity on the public tracker. I have a LOT of accessibility issues to raise but don't know if they are known or not. I can't even see pull request where they were merged to understand the logic behind the breaking changes  as they  look like direct commits

**Comment by TobsBobs** [comment]
I think it´s time to make it public!

**Comment by HLeithner** [comment]
It is public?

**Comment by brianteeman** [comment]
@HLeithner What I meant is that there is no public pull request (that I can find) where the changes to this file https://github.com/joomla/backend-template/commits/release/administrator/templates/atum/scss/blocks/_global.scss were made, discussed and tested etc so that I can comment that the code on line 163 is completely wrong

This is just an example

**Comment by HLeithner** [comment]
my comment was for @TobsBobs 

some commits has been made directly into the branch without PR. Atleast I think so.

**Comment by HLeithner** [comment]
But you can create an issue for every problem you like to report or like to fix.

**Comment by brianteeman** [comment]
That's really bad practice and why there are so many obvious mistakes in the code that wouldnt have passed even a cursory review.

**Comment by HLeithner** [comment]
I think strategy was to get the layout done and fix afterwards.

**Comment by brianteeman** [comment]
> I think strategy was to get the layout done and fix afterwards.

and thats why there are so many obvious mistakes that cant even easily be tracked down to establish what the developers intent was. Without that information its a waste of peoples time trying to fix things. If everything had been done with pull requests we could see what the intent was and create a fix.

**Comment by HLeithner** [comment]
Normal PR you get an overview of all changes when you create a PR against 4.0-dev see https://github.com/joomla/backend-template/pull/84

**Comment by brianteeman** [comment]
no you get whatever someone wrote in the commit message which may or may not be relevant. It certainly doesnt establish what the intent of the commit was. Anyway not going to waste my time on this. Why should I care about the quality of the code and if it even works if "you" don't

**Comment by brianteeman** [comment]
@HLeithner This article is a great explanation of why commit messages are important (although I prefer real pull requests). If at a minimum this repo had real commit messages then the changelog would be at least meaningful and people are able to review and find things. https://chris.beams.io/posts/git-commit/

**Comment by chmst** [comment]
The biggest performance problem is icom_checkin, it causes all the duplicate queries. And is very time consuming. Mabye the database needs some aditional indexes there but I am working on it and will get the numbers via an ajax request.

**Comment by HLeithner** [comment]
@brianteeman I know how important documentation is. You remember our discussion about a comment for a deprecation?

Anyway that's the wrong place to discuss this, this ticket is about the performance problem and will hopefully get fixed by the template team or by someone else.

**Comment by wilsonge** [comment]
> The biggest performance problem is icom_checkin, it causes all the duplicate queries. And is very time consuming. Mabye the database needs some aditional indexes there but I am working on it and will get the numbers via an ajax request.

It's because it's having to go through every component separately I think. I think we're going to struggle to optimise it a lot more

**Comment by chmst** [comment]
Closed as resolved with pr #143
